services:
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER_APP: ${DB_USER_APP}
      POSTGRES_PASSWORD_APP: ${DB_PASSWORD_APP}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erp-network
    ports:
      - "5432:5432"
  frontend:
    image: frontend-sveltekit
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # Main app port
      - "24678:24678" # HMR server
    environment:
      DATABASE_URL: "postgresql://${DB_USER_APP}:${DB_PASSWORD_APP}@db:5432/${DB_NAME}"
    depends_on:
      - db
    networks:
      - erp-network
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  postgres_data:
  node_modules:

networks:
  erp-network: