FROM oven/bun AS deps
LABEL authors="Michal"

WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/node_modules/.vite
COPY --chown=bun:bun package.json bun.lock ./
RUN bun install

# Install OpenSSL for Prisma and clean up to reduce image size
RUN apt update -y && apt install -y openssl && rm -rf /var/lib/apt/lists/*

FROM oven/bun AS development

WORKDIR /usr/src/app

COPY --chown=bun:bun --from=deps /usr/src/app/node_modules ./node_modules
COPY --chown=bun:bun --from=deps /usr/src/app/package.json ./package.json

COPY --chown=bun:bun . .

RUN bunx prisma generate

USER bun
# Expose port 3000 for the SvelteKit app and 24678 for Vite's HMR
EXPOSE 3000/tcp
EXPOSE 24678/tcp

CMD ["bun", "run", "dev"]